# Generated by Django 3.2 on 2021-05-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_app', '0003_alter_event_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='urlSite',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
