# Generated by Django 3.1.7 on 2021-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eva_app', '0007_auto_20210506_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hora',
            field=models.TimeField(null=True),
        ),
    ]
