# Generated by Django 3.2 on 2021-05-03 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eva_app', '0002_alter_event_urlsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalestranteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventoPalestrado', to='eva_app.event')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUserPalestrante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OuvinteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventoInscrito', to='eva_app.event')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUserOuvinte', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
